
const keymap = {
    "a": "key - a",
    "b": "key - b",
    "c": "key - c",
    "d": "key - d",
    "e": "key - e",
    "f": "key - f",
    "g": "key - g",
    "h": "key - h",
    "i": "key - i",
    "j": "key - j",
    "k": "key - k",
    "l": "key - l",
    "m": "key - m",
    "n": "key - n",
    "o": "key - o",
    "p": "key - p",
    "q": "key - q",
    "r": "key - r",
    "s": "key - s",
    "t": "key - t",
    "u": "key - u",
    "v": "key - v",
    "w": "key - w",
    "x": "key - x",
    "y": "key - y",
    "z": "key - z",
    "1": "key - 1",
    "2": "key - 2",
    "3": "key - 3",
    "4": "key - 4",
    "5": "key - 5",
    "6": "key - 6",
    "7": "key - 7",
    "8": "key - 8",
    "9": "key - 9",
    "0": "key - 0",
};

const soundmap = {
    "a": "a.wav",
    "b": "d.wav",
    "c": ";.wav",
    "d": "f.wav",
    "e": "g.wav",
    "f": "h.wav",
    "g": "j.wav",
    "h": "k.wav",
    "i": "l.wav",
    "j": "a.wav",
    "k": "d.wav",
    "l": ";.wav",
    "m": "f.wav",
    "n": "g.wav",
    "o": "a.wav",
    "p": "j.wav",
    "q": "k.wav",
    "r": "l.wav",
    "s": "a.wav",
    "t": "d.wav",
    "u": ";.wav",  
    "v": "f.wav",
    "w": "g.wav",
    "x": "h.wav",
    "y": "j.wav",
    "z": "k.wav",
    "1": "l.wav",
    "2": "a.wav",
    "3": "d.wav",
    "4": ";.wav",
    "5": "f.wav",
    "6": "g.wav",
    "7": "h.wav",
    "8": "j.wav",
    "9": "k.wav",
    "0": "l.wav",
};
//  Web Audio + MediaRecorder setup
// it starts the entire Web Audio API system.
// It allows you to:

// generate audio
// modify audio
// connect audio nodes
// play sounds
// record microphone input
// synthesize piano sounds

const audioContext = new (window.AudioContext || window.webkitAudioContext)();

// Master gain (volume control)
const masterGain = audioContext.createGain(); // This sets the volume level. // 1 = 100% volume
masterGain.gain.value = 1;

// Destination for recording
const dest = audioContext.createMediaStreamDestination(); //  It converts your piano sounds into a recording stream
// record the audio generated by JavaScript, NOT the microphone.

// Connect masterGain to speakers and recorder
masterGain.connect(audioContext.destination); // This sends your piano sound to:
// 🎧 the speakers / headphones
// So you can hear the piano when you press keys.
masterGain.connect(dest); // This sends the same piano sound into the recording stream: this is what the MediaRecorder records

// MediaRecorder for dest.stream
let mediaRecorder = new MediaRecorder(dest.stream); // It creates a MediaRecorder that records the audio generated by your piano, NOT the microphone.
let recordedChunks = [];
let recordedBlob = null; // will store final recording blob

// When a chunk of audio is available, store it
// This event fires whenever the MediaRecorder has audio data ready.
mediaRecorder.ondataavailable = (e) => {
    if (e.data && e.data.size > 0) {
        recordedChunks.push(e.data);
    }
};

// When recording stops, create a downloadable file URL (but don't auto-download)
mediaRecorder.onstop = () => {
    recordedBlob = new Blob(recordedChunks, { type: "audio/webm" });// All small pieces of sound are combined into one final audio file. (just like combining many small clips into one recording).
    const url = URL.createObjectURL(recordedBlob); // A URL is created for the final audio file, which can be used to play or download the recording.

    // update download link
    const link = document.getElementById("downloadLink"); // This finds the download link element in your HTML.
    // <a id="downloadLink"></a>
// If this tag is missing → NOTHING WILL SHOW.

    if (link) { // If the download link element exists:
         // The link's href attribute is set to the URL of the recorded audio file.
         // This makes the link point to your recording.
        link.href = url; 
        link.download = "piano-recording.webm"; // This sets the filename for when you download the recording.
         // The link is made visible by changing its display style.
         // This allows you to see and click the link to download your recording.
        link.style.display = "inline-block"; // show the link
        link.textContent = "Download Recording"; // set link text
    }

    // enable play button now that we have audio
    const playBtn = document.getElementById("playRecord");
    if (playBtn) {
        playBtn.disabled = false; // This means:
// Before recording → Play button is disabled
// After recording stops → Play button becomes active
    }
};

// Load all sounds into AudioBuffers
// This function loads the sound file for a piano key.
const audioBuffers = {}; // This is an empty object where all loaded piano sounds will be stored.

async function loadSoundForKey(key) { // This function loads the sound for a specific key like: "a", "b", "c", etc.
    const fileName = soundmap[key];
    if (!fileName) return; // no sound for this key
    const response = await fetch(`tunes/${fileName}`);
    const arrayBuffer = await response.arrayBuffer(); // Because the sound file (mp3 / wav) you fetch from the server is downloaded as raw binary data.

// To turn that file into something the Web Audio API can understand, you must first convert it into an ArrayBuffer, which is basically:

// "A bucket of raw sound bytes."
// After that, the browser can decode it into a playable audio format.
    const audioBuffer = await audioContext.decodeAudioData(arrayBuffer); // This line decodes the raw sound bytes into an AudioBuffer, which is a format that the Web Audio API can use to play sounds.
    audioBuffers[key] = audioBuffer; // The decoded AudioBuffer is then stored in the audioBuffers object, using the key (like "a", "b", etc.) as the identifier.
}

async function loadAllSounds() { // . This function loads the sounds for all keys defined in the soundmap.
    const keys = Object.keys(soundmap); // This gets an array of all the keys that have sounds defined in the soundmap.
    for (const key of keys) { // For each key in that array:
         // It calls the loadSoundForKey function to load the sound for that specific key.
         // The await keyword ensures that each sound is fully loaded before moving on to the next one.
         // This prevents overwhelming the browser with too many simultaneous requests.
        try {
            await loadSoundForKey(key);
        } catch (err) {
            console.error("Error loading sound for key:", key, err);
        }
    }
    console.log("All piano sounds loaded.");
}

// Start loading on page load
loadAllSounds();

// Function to play sound via Web Audio
function playSound(key, keyElement) {
    const buffer = audioBuffers[key]; // . Get the loaded sound for that key
    if (!buffer) {
        console.warn("No audio buffer for key:", key);
        return;
    }

    const source = audioContext.createBufferSource(); // This creates a sound player inside Web Audio API.
    source.buffer = buffer;  // Now this source knows which sound to play.

    source.connect(masterGain); // This sends the sound:7
// source → masterGain → speakers + recorder

    if (keyElement) {
        source.onended = () => {
            keyElement.classList.remove("active");
        };
 // This makes animations like:
// key turns white when pressed
// key returns to normal when sound endsv
    }
    source.start(0); // This actually plays the audio.
}

// Keyboard events (updated to use playSound)
document.addEventListener("keydown", function(event) {
    const key = event.key.toLowerCase();
    if (key in keymap){
        const keyElement = document.querySelector(` [data-key="${key}"]`);

        if (keyElement) {
            keyElement.classList.add("active");
            // So the key looks pressed.
           // (You remove this class later in playSound. Remember?)
            if (audioContext.state === "suspended") {
                audioContext.resume();
            } // Browsers sometimes block audio until a user interacts.
            // Pressing any key resumes audioContext so sound plays properly.
            playSound(key, keyElement);
        }
    }
});

document.addEventListener("keyup", function(event) {
    const key = event.key.toLowerCase();
    if (key in keymap) {
        const keyElement = document.querySelector(`[data-key="${key}"]`);

        if (keyElement) {
            keyElement.classList.remove("active");
        }
    }
});

const totalkeys = 24; // 2 octaves
const piano = document.querySelector(".piano");
const keylist = Object.keys(keymap).slice(0, totalkeys);

// One octave pattern (12 notes):
// W  B  W  B  W  W  B  W  B  W  B  W

const octavePattern = [
    "white", "black",
    "white", "black",
    "white", "white",
    "black", "white",
    "black", "white",
    "black", "white"
];
const whiteKeyWidth = 50;
let whiteIndex = 0;
for (let i = 0; i < totalkeys; i++) {
    const k = keylist[i]; // get the key character
    const div = document.createElement("div"); // create a div for the key
    const type = octavePattern[i % 12]; // determine if white or black key
    div.className = "key " + type + " " + keymap[k]; // set classes
    div.dataset.key = k; // set data-key attribute
     // add label
    div.textContent = k.toUpperCase(); 

    if (type === "white") {
        div.style.position = "relative";
        whiteIndex++;
    } else {
        const leftPos = whiteIndex * whiteKeyWidth - 18;
        div.style.position = "absolute";
        div.style.left = leftPos + "px";
        div.style.zIndex = 10;
    }
    piano.appendChild(div);
}
// 7. Recording buttons + play button
const startBtn = document.getElementById("startRecord");
const stopBtn = document.getElementById("stopRecord");
const playBtn = document.getElementById("playRecord");
const downloadLink = document.getElementById("downloadLink");
if (startBtn && stopBtn && playBtn) { // Ensure buttons exist
    stopBtn.disabled = true; // can't stop if not started
     // will be enabled after recording stops
    playBtn.disabled = true; // can't play until we have a recording
     // hide download link initially
    if (downloadLink) { 
        downloadLink.style.display = "none"; 
    }

    startBtn.addEventListener("click", () => { // Start recording
        if (mediaRecorder.state === "recording") return; // already recording

        recordedChunks = []; // reset chunks
        recordedBlob = null; // reset blob

        // hide download link
        if (downloadLink) {
            downloadLink.style.display = "none"; // hide link until we have a new recording
        }

        audioContext.resume(); // ensure audio context is running
        mediaRecorder.start(); // start recording
        console.log("Recording started"); // Debug message

         // update button states
        startBtn.disabled = true; // can't start again until stopped
        stopBtn.disabled = false; // can stop now
         // playBtn remains disabled until we have a recording
        playBtn.disabled = true; // can't play until we have a recording
    });

    stopBtn.addEventListener("click", () => { // Stop recording
        if (mediaRecorder.state === "inactive") return; // not recording

         // stop recording
        mediaRecorder.stop(); 
        console.log("Recording stopped");
        stopBtn.disabled = true; // can't stop again until started
         // enable startBtn to allow new recording
        startBtn.disabled = false;
        // playBtn gets enabled in mediaRecorder.onstop after blob is ready
    });

    // 🔹 Play the recorded audio (no download)
    playBtn.addEventListener("click", () => { // Play recording
        if (!recordedBlob) { // no recording yet
            console.warn("No recording available to play yet."); // Debug message
            return; 
        }

        const url = URL.createObjectURL(recordedBlob); // create URL for blob
         // create audio element to play
        const audio = new Audio(url); // This creates a new audio element in JavaScript that will play the recorded audio.
         // play the audio
        audio.play();
        console.log("Playing recorded audio");
    });
}
